<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>ESGCrystalViewer</RootNamespace>
    <AssemblyName>ESGCrystalViewer</AssemblyName>
    <StartupObject>ESGCrystalViewer.Program</StartupObject>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <MyType>WindowsForms</MyType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CrystalReports.ReportSource" Version="13.0.4003" />
    <PackageReference Include="CrystalReports.Shared" Version="13.0.4003" />
    <PackageReference Include="CrystalReports.Windows.Forms" Version="13.0.4003" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System">
      <HintPath>..\..\..\..\..\..\..\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\System.dll</HintPath>
    </Reference>
    <Reference Include="System.Data" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Xml" />
  </ItemGroup>
</Project>